### PR TITLE
Send PHP errors to ratchet.io

### PR DESCRIPTION
**Pull request by sergebezborodov**
For some applications is also important handling php errors.
I add code to RatchetioErrorHandler, by default php errors is disabled, by setting phpErrorsToRatchetio to true its enable.

### CODE REVIEW

**Comment by samdark** [comment]
Something's wrong with line ending and/or tabs/spaces. Other than that, useful.

**Comment by sergebezborodov** [comment]
added commit with converted spaces to tabs

**Comment by samdark** [comment]
I'm thinking about enabling it by default and removing option. It doesn't make sense to send exceptions to ratchet and avoid errors.

**Comment by sergebezborodov** [comment]
I think too about it, but maybe exist projects with 'bad smells' that disable yii_error_handler by default and ignore php errors.

**Comment by samdark** [comment]
I don't think we should worry about if. If someone will experience it, we'll get an issue filled, I think.

**Comment by sergebezborodov** [comment]
you're right, added new commit

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by kirs** [comment]
Great, thanks!

**Pull request merged**
